# Source .bashrc and .profile instead
# export PATH="/Users/michaelyang/miniconda3/bin:$PATH"

if [ -f ~/.profile ]; then
   source ~/.profile
fi

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# added by Miniconda3 installer
# export PATH="/Users/michaelyang/miniconda3/bin:$PATH"

# absolutely no clue why this works here, and not in bashrc (even with $PATH updated before)
# alias notebook='jupyter notebook'

# The next line updates PATH for the Google Cloud SDK.
# if [ -f '/Users/michaelyang/google-cloud-sdk/path.bash.inc' ]; then source '/Users/michaelyang/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/michaelyang/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/michaelyang/google-cloud-sdk/completion.bash.inc'; fi

# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
