# Source .bashrc and .profile instead

if [ -f ~/.profile ]; then
   source ~/.profile
fi

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# For Mac OS
if [ "$(uname)" == "Darwin" ]; then
  # Required by Homebrew
  eval "$(/opt/homebrew/bin/brew shellenv)"
  
  # load chruby
  source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
fi

eval "$(rbenv init - bash)"
